sudo: required

language: generic

services:
  - docker

git:
  quiet: true
  submodules: true

notifications:
  email:
    on_success: never
    on_failure: never

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
    - ROS_REPO=ros
    - CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Debug"

jobs:
  include:
    - os: linux
      dist: focal
      language: cpp
      env:
      - ROS_DISTRO="noetic"
      - CLANG_FORMAT_CHECK=file
      - CLANG_FORMAT_VERSION=8
      cache:
        directories:
          - $HOME/.ccache

    - os: linux
      dist: focal
      language: cpp
      env:
      - ROS_DISTRO="noetic"
      - BADGE="noetic"
      - ROSDEP_SKIP_KEYS="cmake_common_scripts"
      - DOCKER_IMAGE="ros:noetic"
      - ADDITIONAL_DEBS="qt5-default libqt5scxml5-dev libqt5scxml5-bin qtdeclarative5-dev"
      - UPSTREAM_WORKSPACE="dependencies.rosinstall"
      - TARGET_CMAKE_ARGS="-DSCXML_CORE_ENABLE_TESTING=ON"
      cache:
        directories:
          - $HOME/.ccache

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master

script:
  - .industrial_ci/travis.sh
