##################################################################################################
#
# CMake script for finding Qt5Scxml.
#
# Input variables:
#
# - Qt5Scxml_ROOT_DIR (optional): When specified, header files and libraries will be searched for in
#     ${Qt5Scxml_ROOT_DIR}/include
#     ${Qt5Scxml_ROOT_DIR}/libs
#   respectively, and the default CMake search order will be ignored. When unspecified, the default
#   CMake search order is used.
#   This variable can be specified either as a CMake or environment variable. If both are set,
#   preference is given to the CMake variable.
#   Use this variable for finding packages installed in a nonstandard location, or for enforcing
#   that one of multiple package installations is picked up.
#
#
# Cache variables (not intended to be used in CMakeLists.txt files)
#
# - Qt5Scxml_INCLUDE_DIR: Absolute path to package headers.
# - Qt5Scxml_LIBRARY: Absolute path to library.
#
#
# Output variables:
#
# - Qt5Scxml_FOUND: Boolean that indicates if the package was found
# - Qt5Scxml_INCLUDE_DIRS: Paths to the necessary header files
# - Qt5Scxml_LIBRARIES: Package libraries
#
#
# Example usage:
#
#  find_package(Qt5Scxml)
#  if(NOT Qt5Scxml_FOUND)
#    # Error handling
#  endif()
#  ...
#  include_directories(${Qt5Scxml_INCLUDE_DIRS} ...)
#  ...
#  target_link_libraries(my_target ${Qt5Scxml_LIBRARIES})
#
##################################################################################################

# Get package location hint from environment variable (if any)
if(NOT Qt5Scxml_ROOT_DIR AND DEFINED ENV{Qt5Scxml_ROOT_DIR})
  set(Qt5Scxml_ROOT_DIR "$ENV{Qt5Scxml_ROOT_DIR}" CACHE PATH
      "Qt5Scxml base directory location (optional, used for nonstandard installation paths)")
endif()

# Search path for nonstandard package locations
if(Qt5Scxml_ROOT_DIR)
  set(Qt5Scxml_INCLUDE_PATH PATHS "${Qt5Scxml_ROOT_DIR}/include" NO_DEFAULT_PATH)
  set(Qt5Scxml_LIBRARY_PATH PATHS "${Qt5Scxml_ROOT_DIR}/lib"     NO_DEFAULT_PATH)
endif()

# Find headers and libraries
find_path(Qt5Scxml_INCLUDE_DIR NAMES Qt5Scxml.h PATH_SUFFIXES "Qt5Scxml" ${Qt5Scxml_INCLUDE_PATH})
find_library(Qt5Scxml_LIBRARY  NAMES Qt5Scxml   PATH_SUFFIXES "Qt5Scxml" ${Qt5Scxml_LIBRARY_PATH})

mark_as_advanced(Qt5Scxml_INCLUDE_DIR
                 Qt5Scxml_LIBRARY)

# Output variables generation
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Qt5Scxml DEFAULT_MSG Qt5Scxml_LIBRARY
                                                       Qt5Scxml_INCLUDE_DIR)

set(Qt5Scxml_FOUND ${Qt5Scxml_FOUND}) # Enforce case-correctness: Set appropriately cased variable...
unset(Qt5Scxml_FOUND) # ...and unset uppercase variable generated by find_package_handle_standard_args

if(Qt5Scxml_FOUND)
  set(Qt5Scxml_INCLUDE_DIRS ${Qt5Scxml_INCLUDE_DIR})
  set(Qt5Scxml_LIBRARIES ${Qt5Scxml_LIBRARY})
endif()
